{
  "formatVersion": "1.1",
  "component": {
    "group": "com.edfapay",
    "module": "edfapg_sdk",
    "version": "0.0.3-sc2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded-core"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        },
        {
          "group": "com.appmattus.crypto",
          "module": "cryptohash",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "library-metadata-0.0.3-sc2.jar",
          "url": "edfapg_sdk-0.0.3-sc2.jar",
          "size": 74701,
          "sha512": "f9f1e116a395b57252c63dc238f6fcbc7f003cd8cdaf6efeb68427f3f00e3cd0526db8c49b0bc5194015e032e37d7be83025522db9e69a089dde8fa012b51321",
          "sha256": "c80a4fbcb1da868c4e86dc69cf6720ce52cdef6bda5d90c4e2bc5661d898eee6",
          "sha1": "8bc21733f28b961ce706e61eed8535a5fcfcf3f9",
          "md5": "1122ca875e912eed5228bb10a056d0a8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "library-kotlin-0.0.3-sc2-sources.jar",
          "url": "edfapg_sdk-0.0.3-sc2-sources.jar",
          "size": 72839,
          "sha512": "c7765da47cd700db4a500cb6962c71aeca3cfc002399915f340c5a2322b65e28db1a5c7099cd34fc6ae958824478906e9b862f12cf517df5cb90a6c7b38dc916",
          "sha256": "6afb565c781a7bcf4cbba1329916ecf7fdceb3d61d16789122fa8134cd9c630c",
          "sha1": "763d34d92e3daa7172f75a6a586583515ecee968",
          "md5": "f6ebeeac22d54e276769266815bdc498"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-android/0.0.3-sc2/edfapg_sdk-android-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-android",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-android/0.0.3-sc2/edfapg_sdk-android-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-android",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-android/0.0.3-sc2/edfapg_sdk-android-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-android",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosarm64/0.0.3-sc2/edfapg_sdk-iosarm64-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosarm64",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosarm64/0.0.3-sc2/edfapg_sdk-iosarm64-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosarm64",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosarm64/0.0.3-sc2/edfapg_sdk-iosarm64-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosarm64",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosarm64/0.0.3-sc2/edfapg_sdk-iosarm64-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosarm64",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iossimulatorarm64/0.0.3-sc2/edfapg_sdk-iossimulatorarm64-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iossimulatorarm64",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iossimulatorarm64/0.0.3-sc2/edfapg_sdk-iossimulatorarm64-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iossimulatorarm64",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iossimulatorarm64/0.0.3-sc2/edfapg_sdk-iossimulatorarm64-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iossimulatorarm64",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iossimulatorarm64/0.0.3-sc2/edfapg_sdk-iossimulatorarm64-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iossimulatorarm64",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosx64/0.0.3-sc2/edfapg_sdk-iosx64-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosx64",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosx64/0.0.3-sc2/edfapg_sdk-iosx64-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosx64",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosx64/0.0.3-sc2/edfapg_sdk-iosx64-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosx64",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosx64/0.0.3-sc2/edfapg_sdk-iosx64-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosx64",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-jvm/0.0.3-sc2/edfapg_sdk-jvm-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-jvm",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-jvm/0.0.3-sc2/edfapg_sdk-jvm-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-jvm",
        "version": "0.0.3-sc2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-jvm/0.0.3-sc2/edfapg_sdk-jvm-0.0.3-sc2.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-jvm",
        "version": "0.0.3-sc2"
      }
    }
  ]
}
