{
  "formatVersion": "1.1",
  "component": {
    "group": "com.edfapay",
    "module": "edfapg_sdk",
    "version": "0.0.3-sc1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded-core"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        },
        {
          "group": "com.appmattus.crypto",
          "module": "cryptohash",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "library-metadata-0.0.3-sc1.jar",
          "url": "edfapg_sdk-0.0.3-sc1.jar",
          "size": 74701,
          "sha512": "f9f1e116a395b57252c63dc238f6fcbc7f003cd8cdaf6efeb68427f3f00e3cd0526db8c49b0bc5194015e032e37d7be83025522db9e69a089dde8fa012b51321",
          "sha256": "c80a4fbcb1da868c4e86dc69cf6720ce52cdef6bda5d90c4e2bc5661d898eee6",
          "sha1": "8bc21733f28b961ce706e61eed8535a5fcfcf3f9",
          "md5": "1122ca875e912eed5228bb10a056d0a8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "library-kotlin-0.0.3-sc1-sources.jar",
          "url": "edfapg_sdk-0.0.3-sc1-sources.jar",
          "size": 72746,
          "sha512": "fb1807e648be29740d7bb671085658a8f16baf3bd59a9a2035672a17476e55677820ad02e619ce20d788c1bd52131ac5d94a5fe36fc34fff0e01be6d8d9a4b7e",
          "sha256": "a61db9f19c63acd9632b3abfd3de6575e9b1ff86ba1110eeb33dcb00f577755e",
          "sha1": "a9489e3ed3d9f07d12ee826cf89339d497f82255",
          "md5": "3fca9125c4b939766021d72c1ce6c8ba"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-android/0.0.3-sc1/edfapg_sdk-android-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-android",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-android/0.0.3-sc1/edfapg_sdk-android-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-android",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-android/0.0.3-sc1/edfapg_sdk-android-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-android",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosarm64/0.0.3-sc1/edfapg_sdk-iosarm64-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosarm64",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosarm64/0.0.3-sc1/edfapg_sdk-iosarm64-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosarm64",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosarm64/0.0.3-sc1/edfapg_sdk-iosarm64-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosarm64",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosarm64/0.0.3-sc1/edfapg_sdk-iosarm64-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosarm64",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iossimulatorarm64/0.0.3-sc1/edfapg_sdk-iossimulatorarm64-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iossimulatorarm64",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iossimulatorarm64/0.0.3-sc1/edfapg_sdk-iossimulatorarm64-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iossimulatorarm64",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iossimulatorarm64/0.0.3-sc1/edfapg_sdk-iossimulatorarm64-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iossimulatorarm64",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iossimulatorarm64/0.0.3-sc1/edfapg_sdk-iossimulatorarm64-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iossimulatorarm64",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosx64/0.0.3-sc1/edfapg_sdk-iosx64-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosx64",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosx64/0.0.3-sc1/edfapg_sdk-iosx64-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosx64",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosx64/0.0.3-sc1/edfapg_sdk-iosx64-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosx64",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosx64/0.0.3-sc1/edfapg_sdk-iosx64-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosx64",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-jvm/0.0.3-sc1/edfapg_sdk-jvm-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-jvm",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-jvm/0.0.3-sc1/edfapg_sdk-jvm-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-jvm",
        "version": "0.0.3-sc1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-jvm/0.0.3-sc1/edfapg_sdk-jvm-0.0.3-sc1.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-jvm",
        "version": "0.0.3-sc1"
      }
    }
  ]
}
