{
  "formatVersion": "1.1",
  "component": {
    "url": "../../edfapg_sdk/0.0.1-alpha.4/edfapg_sdk-0.0.1-alpha.4.module",
    "group": "com.edfapay",
    "module": "edfapg_sdk",
    "version": "0.0.1-alpha.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "library-jvm-0.0.1-alpha.4.jar",
          "url": "edfapg_sdk-jvm-0.0.1-alpha.4.jar",
          "size": 2646532,
          "sha512": "bfc712d9632c8816dcf688abc0b5558b3ce6557af15edabdeb3887f7f148e568c5b2ff8c90d73724efeb7aa8c37472a799df6b59857d4d9352f41120647c079f",
          "sha256": "66b1bbf2d0e34d3d0c1ad09f8bd9e84d2cd0f6e69f3a17b41273949812dc4dd4",
          "sha1": "f6d99ef2a67062957c3070ea0d7e66489ddd878d",
          "md5": "ac1bc04a44ee63f2d3f8e0a8114d21ee"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded-core"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        },
        {
          "group": "com.appmattus.crypto",
          "module": "cryptohash",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.6"
          }
        }
      ],
      "files": [
        {
          "name": "library-jvm-0.0.1-alpha.4.jar",
          "url": "edfapg_sdk-jvm-0.0.1-alpha.4.jar",
          "size": 2646532,
          "sha512": "bfc712d9632c8816dcf688abc0b5558b3ce6557af15edabdeb3887f7f148e568c5b2ff8c90d73724efeb7aa8c37472a799df6b59857d4d9352f41120647c079f",
          "sha256": "66b1bbf2d0e34d3d0c1ad09f8bd9e84d2cd0f6e69f3a17b41273949812dc4dd4",
          "sha1": "f6d99ef2a67062957c3070ea0d7e66489ddd878d",
          "md5": "ac1bc04a44ee63f2d3f8e0a8114d21ee"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "library-jvm-0.0.1-alpha.4-sources.jar",
          "url": "edfapg_sdk-jvm-0.0.1-alpha.4-sources.jar",
          "size": 72413,
          "sha512": "df228f3d15174fdc2e848fc1df266f5a7aa36f444d79454cbfdae4a9d68ee4de9736a5bf3856d40fd4c3ba265f3b2c15ae3b6c4e43c7c9a8750d7c301ee4e963",
          "sha256": "bbcbec4bf5b14663c25852086d5aca03ef4a040b6bb10d1609f7c400b77747ab",
          "sha1": "8937a0352abe77292003d23d6524f302ed77aa2c",
          "md5": "12e9a425589949ca7f7dc2c2214ffee7"
        }
      ]
    }
  ]
}
