{
  "formatVersion": "1.1",
  "component": {
    "group": "com.edfapay",
    "module": "edfapg_sdk",
    "version": "0.0.1-alpha.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded-core"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        },
        {
          "group": "com.appmattus.crypto",
          "module": "cryptohash",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "library-metadata-0.0.1-alpha.4.jar",
          "url": "edfapg_sdk-0.0.1-alpha.4.jar",
          "size": 73791,
          "sha512": "8354c55e26618a77df3baeb4094ff52201480eeb4b728f1dce5c091db6b4aa01477d048c9f2abde1b98219cdab957fa1476628c20245d8a4eaafa4815aa75cb6",
          "sha256": "3f5bd5002d70531bd1fdb1af7fc2dc1465adf45460a6898f72dab9bcdba76ed7",
          "sha1": "bf5b8e2a073b9dce3d94c4b4e76ab95cb771283f",
          "md5": "a2fa395087b9138b2e30e7ce8d87411a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "library-kotlin-0.0.1-alpha.4-sources.jar",
          "url": "edfapg_sdk-0.0.1-alpha.4-sources.jar",
          "size": 73301,
          "sha512": "aeaf5df8baa182ca5ffc7c54896f73e509e3cf460b518b7c6ea2fc86c71649d7af7cf6540993471d5224960b04ad6fbdefdd0b855c514a2ce882f99fc0ce1c17",
          "sha256": "3f173aa683561eceb05d300900f2f8bbdbf7a272fd24d164aa97a30db2188c9e",
          "sha1": "52811f862e8d42bf1ce0a0b4a877a8eaded8c8b2",
          "md5": "0b8ee7746b82132d1db47913b936b661"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-android/0.0.1-alpha.4/edfapg_sdk-android-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-android",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-android/0.0.1-alpha.4/edfapg_sdk-android-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-android",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-android/0.0.1-alpha.4/edfapg_sdk-android-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-android",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosarm64/0.0.1-alpha.4/edfapg_sdk-iosarm64-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosarm64",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosarm64/0.0.1-alpha.4/edfapg_sdk-iosarm64-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosarm64",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosarm64/0.0.1-alpha.4/edfapg_sdk-iosarm64-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosarm64",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosarm64/0.0.1-alpha.4/edfapg_sdk-iosarm64-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosarm64",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iossimulatorarm64/0.0.1-alpha.4/edfapg_sdk-iossimulatorarm64-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iossimulatorarm64",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iossimulatorarm64/0.0.1-alpha.4/edfapg_sdk-iossimulatorarm64-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iossimulatorarm64",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iossimulatorarm64/0.0.1-alpha.4/edfapg_sdk-iossimulatorarm64-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iossimulatorarm64",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iossimulatorarm64/0.0.1-alpha.4/edfapg_sdk-iossimulatorarm64-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iossimulatorarm64",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosx64/0.0.1-alpha.4/edfapg_sdk-iosx64-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosx64",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosx64/0.0.1-alpha.4/edfapg_sdk-iosx64-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosx64",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "iosX64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosx64/0.0.1-alpha.4/edfapg_sdk-iosx64-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosx64",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../edfapg_sdk-iosx64/0.0.1-alpha.4/edfapg_sdk-iosx64-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-iosx64",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-jvm/0.0.1-alpha.4/edfapg_sdk-jvm-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-jvm",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-jvm/0.0.1-alpha.4/edfapg_sdk-jvm-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-jvm",
        "version": "0.0.1-alpha.4"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../edfapg_sdk-jvm/0.0.1-alpha.4/edfapg_sdk-jvm-0.0.1-alpha.4.module",
        "group": "com.edfapay",
        "module": "edfapg_sdk-jvm",
        "version": "0.0.1-alpha.4"
      }
    }
  ]
}
