{
  "formatVersion": "1.1",
  "component": {
    "url": "../../edfapg_sdk/0.0.2-size2/edfapg_sdk-0.0.2-size2.module",
    "group": "com.edfapay",
    "module": "edfapg_sdk",
    "version": "0.0.2-size2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "library-jvm-0.0.2-size2.jar",
          "url": "edfapg_sdk-jvm-0.0.2-size2.jar",
          "size": 2661000,
          "sha512": "9f5ee2b975e3ca37bce36a7273e8279ef5ec3116f79fefd1463140ab49d81a5bfe5eaba3c6eddc86cd9ebce8189225a03a0059eadd4cc052df06a4e7aab22f5d",
          "sha256": "69b538fa8e04cb4dd4ced3ae2dbf5b12a8eb825e757228190b9aa4e1f7986cd5",
          "sha1": "2f29dbdb5b40b046934197298694fc96fce209ce",
          "md5": "695119ca100d38e4dbdcc11fbe2d1051"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded-core"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        },
        {
          "group": "com.appmattus.crypto",
          "module": "cryptohash",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.6"
          }
        }
      ],
      "files": [
        {
          "name": "library-jvm-0.0.2-size2.jar",
          "url": "edfapg_sdk-jvm-0.0.2-size2.jar",
          "size": 2661000,
          "sha512": "9f5ee2b975e3ca37bce36a7273e8279ef5ec3116f79fefd1463140ab49d81a5bfe5eaba3c6eddc86cd9ebce8189225a03a0059eadd4cc052df06a4e7aab22f5d",
          "sha256": "69b538fa8e04cb4dd4ced3ae2dbf5b12a8eb825e757228190b9aa4e1f7986cd5",
          "sha1": "2f29dbdb5b40b046934197298694fc96fce209ce",
          "md5": "695119ca100d38e4dbdcc11fbe2d1051"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "library-jvm-0.0.2-size2-sources.jar",
          "url": "edfapg_sdk-jvm-0.0.2-size2-sources.jar",
          "size": 71926,
          "sha512": "6534aec57c753029d157063504aeeee3ad75979b92bfed7e791cbfcbfec261c658b90ed20ef20d3c37e62600bc97fdb150e189f71180934dbbb87face14d46e9",
          "sha256": "88f60617a473d9e87cd91708c52e61c076c7fe5f707725d292eb6183dbdde467",
          "sha1": "a1a2d0c713b4161fc1bae4a8c7ed0c6c6f035924",
          "md5": "c583a0183f9fd258ac113ee01f5d6b03"
        }
      ]
    }
  ]
}
