{
  "formatVersion": "1.1",
  "component": {
    "url": "../../edfapg_sdk/0.0.1/edfapg_sdk-0.0.1.module",
    "group": "com.edfapay",
    "module": "edfapg_sdk",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded-core"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        },
        {
          "group": "com.appmattus.crypto",
          "module": "cryptohash",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.6"
          }
        }
      ],
      "files": [
        {
          "name": "library-iosSimulatorArm64Main-0.0.1.klib",
          "url": "edfapg_sdk-iossimulatorarm64-0.0.1.klib",
          "size": 566004,
          "sha512": "1b3b0358bdbf27063f7bc82d808429f961bcdf2ad511bf50552c9219aa6f0accb81f1f6474f4f139f5186a9fb314704bccf7c27c7f366094aee74dce9b8dc84a",
          "sha256": "54afa4701e5d6efacdb34f66d7c7d201f4ccc67fff8804b2070ad4c7bbce47bd",
          "sha1": "d4467b81f34ac85c036c61c766e45cedfafb9cc2",
          "md5": "4aa713bfc07ac123088006456a510a5f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "library-iossimulatorarm64-0.0.1-sources.jar",
          "url": "edfapg_sdk-iossimulatorarm64-0.0.1-sources.jar",
          "size": 84946,
          "sha512": "c58417ae72a35c57c0044993517fe1602f71708c9b90fced7a2dc2c481d1d37d6dc91da8addc87ebafe11b0b7528627c23bb2ce7dff6484a99e53c307bd66777",
          "sha256": "40f00215d8f517b1926e18ddb8580186e0868a7e0c7da935e3a8b426f9ed8a25",
          "sha1": "28b43cf43ed7bf54951a6989fbcb4a33675a97dd",
          "md5": "32375fbaf40ec69b99bae5ac4b0e71bd"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded-core"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        },
        {
          "group": "com.appmattus.crypto",
          "module": "cryptohash",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.6"
          }
        }
      ],
      "files": [
        {
          "name": "library-0.0.1.kotlin_resources.zip",
          "url": "edfapg_sdk-iossimulatorarm64-0.0.1-kotlin_resources.kotlin_resources.zip",
          "size": 2165702,
          "sha512": "4945caadd9344992e5e46941200b9a65bf30612fe694180468219bbc0f77c33442dc0608ee33fe085c5474e1bf354a17adeb643d49b0a93bb669766e144bb074",
          "sha256": "85d439cc0c5cbd48c7b7a5e93c6b84faf8b43a9dbac48e31af19654f249927f1",
          "sha1": "d072be917d636a73a0ed3b260d517afbda0449b8",
          "md5": "4d861b4593a9602c0c0ff1a2545a6174"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.3"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded-core"
          }
        },
        {
          "group": "tech.annexflow.compose",
          "module": "constraintlayout-compose-multiplatform",
          "version": {
            "requires": "0.6.1-shaded"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        },
        {
          "group": "com.appmattus.crypto",
          "module": "cryptohash",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.6"
          }
        }
      ],
      "files": [
        {
          "name": "library-iossimulatorarm64-0.0.1-metadata.jar",
          "url": "edfapg_sdk-iossimulatorarm64-0.0.1-metadata.jar",
          "size": 5554,
          "sha512": "693127d66df357099d8427407a77a804ed3cb335512e31a70914119a8f37e395f40d1c6a3d4568fb76c048a0180ae64f1f39d0db87b32788e323093928624c5a",
          "sha256": "074010cfa1ef38af82e79e2a39fb49346104cf7e0e8afb2e8d6809b6449093a3",
          "sha1": "5a79e0be3ceb4f58a86a70e749ac2be4385e1c3a",
          "md5": "21af52a0dd38555ec87e5abef93116eb"
        }
      ]
    }
  ]
}
